src/users/blogs/models.py
from users.utils.generator.id_generator import gen_id
from users.posts.models import Post
from users.drafts.model import Draft
from users.records.record import Record
from users.utils.generator.date_generator import time_now as date_created
from users.utils.html_stripper import strip_html_tags


class ParentBlog(object):
    """ ParentBlog: class

    Each user on the application has a parent blog and from the parent blog
    many child blogs can be generated. This class SHOULD only be accessed
    from the user blog class and not directly.
    """

    def __init__(self, user_id):
        self._user_id = user_id

    def create_blog(self, blog_form):
        """create_blog(blog form object) -> returns child blog object
        Creates a child blog that allows the user to either create or delete a post

        :param
            `blog_form`: The post details which include the title, post content
        :returns
            Returns a blog object
        """
        child_blog_id = gen_id()
        blog_data = self._to_json(blog_form, child_blog_id, date_created)

        if not Record.save(blog_data):
            raise Exception('Error, The blog data was not saved on the database.')
        return _ChildBlog(self._user_id, child_blog_id,
                          blog_form.blog_name.data, blog_form.title.data,
                          blog_form.description.data, _id=None, blog_live=True,
                          date_created=date_created
                          )

    @staticmethod
    def find_child_blog(child_blog_id):
        """Takes a child blog id and if found returns that blog as an object"""

        data = Record.Query.Filter.filter_by_key_and_value({"child_blog_id": child_blog_id})
        return _ChildBlog(**data) if data else None

    def find_all_child_blogs(self):
        """Returns all child blog created by this parent blog"""

        blogs = Record.Query.find_all(query={"user_id": self._user_id, "blog_live": True})
        return [_ChildBlog(**blog) for blog in blogs] if blogs else None

    def delete_all_child_blogs(self):
        """Deletes all blogs and all posts, drafts and cooments associated with the blogs"""

        data = [{"user_id": self._user_id, "blog_live": True},  # Delete all blogs created by the user
                {"user_id": self._user_id, "post_live": True},  # Delete all post created by the user
                {"user_id": self._user_id, "collection_name": "draft"}, # Delete all drafts created by the user
                {"user_id": self._user_id, "comment_live":True}, # Delete all comments created by the user
                ]
        Record.Delete.delete_all_blogs(data=data)

    def _to_json(self, blog_form, child_blog_id, date_created):
        """"""
        return {
                "user_id": self._user_id,
                "child_blog_id": child_blog_id,
                "blog_name": blog_form.blog_name.data,
                "title": blog_form.title.data,
                "description": blog_form.description.data,
                "blog_live": True,
                "date_created": date_created()
                }


class _ChildBlog(object):
    """The Child blog is a child of the Parent blog and
       should not be called directly. It is also a container.
    """

    def __init__(self, user_id, child_blog_id, blog_name,
                 title, description, _id, blog_live, date_created):

        self.child_blog_id = child_blog_id
        self.blog_name = blog_name
        self.title = title
        self.description = description
        self.date_created = date_created
        self._id = _id
        self._user_id = user_id
        self._blog_live = blog_live
        self.Post = Post(user_id, child_blog_id)

    @staticmethod
    def html_strip(text):
        return strip_html_tags(text)

    def update_blog(self, data):
        """Finds a specific blog by ID and updates that blog using the new data"""
        Record.Update.update(field_name='child_blog_id', field_id=self.child_blog_id, data=data)

    def delete_blog(self):
        """Deletes a blog by ID"""
        Record.Delete.delete_blog(self.child_blog_id)

src/users/blogs/views.py
from flask import Blueprint, render_template, url_for, redirect, abort

from users.blogs.form import BlogForm
from users.decorators import login_required
from users.users.users import UserBlog
from users.utils.generator.msg import Message

blogs_app = Blueprint('blogs_app', __name__, url_prefix="/blogs")


@blogs_app.route('/', methods=['GET', 'POST'])
@login_required
def blog():
    """Displays all the blogs created by the user"""
    blog = UserBlog()
    return render_template('blogs/blogs.html', blogs=blog.get_all_blogs())


@blogs_app.route('/create', methods=['GET', 'POST'])
@login_required
def blog_create():
    """Allows the user to create a brand new blog."""

    form = BlogForm()

    if form.validate_on_submit():

        blog = UserBlog()
        blog.create_blog(form)
        Message.display_to_gui_screen("A new blog was successfully created.")
        return redirect(url_for("blogs_app.blog"))

    return render_template('blogs/blog.html', form=form, edit_blog=False)


@blogs_app.route('/edit/<blog_id>', methods=('GET', 'POST'))
def blog_edit(blog_id):
    """Takes a blog id and edits that blog"""

    blog = UserBlog()
    child_blog = blog.get_blog(blog_id)

    if not child_blog:
        abort(404)

    form = BlogForm(obj=child_blog) # populate the blog form with details from the child blog object

    if form.validate_on_submit():

        blog_data = _get_updated_data(form, child_blog)

        if blog_data:
            child_blog.update_blog(data=blog_data)
            Message.display_to_gui_screen("You have successfully updated your blog.")
            return redirect(url_for("blogs_app.my_blog", blog_id=child_blog.child_blog_id))

    return render_template("blogs/blog.html", form=form, child_blog=child_blog, edit_blog=True)


@blogs_app.route('/')
def my_blog():
    """Takes a blog id and returns that blog"""
    return redirect(url_for('blogs_app.blog'))


@blogs_app.route('/blog/id/<blog_id>/posts')
def blog_posts(blog_id):
    """Takes an id belonging to a blog and returns all post that associated with that blog"""
    return redirect(url_for("posts_app.posts", blog_id=blog_id))


@blogs_app.route('/delete/<blog_id>', methods=['GET', 'POST'])
def blog_delete(blog_id):
    """Deletes a blog using its blog_id"""

    blog = UserBlog()
    child_blog = blog.get_blog(blog_id)
    child_blog.delete_blog()
    Message.display_to_gui_screen("One of your blogs was deleted successfully")
    return redirect(url_for("blogs_app.blog"))


@blogs_app.route('/blogs/all/delete')
def delete_all_blogs():
    """Deletes all blogs created by the user"""

    blog = UserBlog()
    blog.delete_all_blogs()
    Message.display_to_gui_screen("All child blogs relating to this blog have been deleted.")
    return redirect(url_for('blogs_app.blog'))


@blogs_app.route("/front-page")
def blog_front_page():
    """"""
    return render_template("/blogs/front_page.html")


def _get_updated_data(form, blog):
    """get_updated_data(form_obj, blog_obj) -> return dict

    Checks if the user has updated their data. If the data has
    been updated returns only the updated data otherwise returns
    an empty dictionary.
    """

    data = {}

    if form.blog_name.data != blog.blog_name:
        data.update({"blog_name": form.blog_name.data})
    if form.title.data != blog.title:
        data.update({"title": form.title.data})
    if form.description.data != blog.description:
        data.update({"description": form.description.data})
    return data

src/templates/blogs/blog.html
{% extends "index.html" %}

{% block title %} Blog {% endblock %}

{% block body %}

<div class="container">
    <div id='creation' class="row">

        {% include "dashboard/dashboard.html" %}

        <div class="col-md-offset-1 col-lg-9">


            {% include "__flash_messages.html" %}
            {% from "__formhelpers.html" import render_field %}

            {% if edit_blog %}
            <h3 class="panel-title">Edit Blog</h3>
            {% else %}
            <h3 class="panel-title">Create A New Blog</h3>
            {% endif %}

            <form method="POST" role="form">

                {{ form.hidden_tag() }} <!-- prevent cross-site scripting -->
                {{ render_field(form.blog_name, class='form-control') }}
                {{ render_field(form.title, class='form-control') }}
                {{ render_field(form.description, rows="20", class='form-control') }}
                <br>

                {% if edit_blog %}
                <button type="submit"
                        formaction="{{ url_for('blogs_app.blog_edit', blog_id=child_blog.child_blog_id) }}">Save
                </button>
                {% else %}
                <button type="submit" name="new_blog" formaction="{{ url_for('blogs_app.blog_create') }}">Create new
                    blog
                </button>
                {% endif %}

            </form>


        </div>
    </div>
</div>

{% endblock %}

src/templates/blogs/blogs.html
{% extends "index.html" %}

{% block body %}

<!-- ToDo
    Add Bootsrap styling to the page to make it more pleasing to the eye.
-->

<br>
<div class="container">
    <div class="row">

        <div class="col-md-12">

            {% if blogs %}

            {% include "__flash_messages.html" %}

             <div class="jumbotron">
                 To create a post within a blog click on the <strong>blog name</strong> of your choice
            </div>
            <br>

            <h3><u>List of blogs</u></h3>


            <table class="table table-striped">

                <thead>
                <tr>
                    <th>#</th>
                    <th>Blog Name</th>
                    <th>Title</th>
                    <th>Description</th>
                    <th>Creation date</th>
                    <th>Edit/Delete</th>
                </tr>
                </thead>

                <tbody>

                {% for blog in blogs %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <td><a href="{{ url_for('blogs_app.blog_posts', blog_id=blog.child_blog_id) }}">{{ blog.blog_name  | truncate(20) | safe }}<a/></td>
                    <td>{{ blog.html_strip(blog.title) | truncate(20) }}</td>
                    <td>{{ blog.html_strip(blog.description) | truncate(40)  }} </td>
                    <td>{{ blog.date_created.strftime('%c') }} </td>
                    <td>

                        <a href="{{ url_for('blogs_app.blog_edit', blog_id=blog.child_blog_id) }}"><button>Edit</button></a>
                        |
                        <a href="{{ url_for('blogs_app.blog_delete', blog_id=blog.child_blog_id) }}/"><button>Delete</button></a>

                    </td>
                </tr>
                {% endfor %}


                </tbody>

            </table>
            {% else %}
            <div class="jumbotron">
                You currently have no blogs
            </div>
            {% endif %}

            <a href="{{ url_for('blogs_app.blog_create') }}"><button>Create Blog</button></a>
            <a href="{{ url_for('blogs_app.delete_all_blogs') }}"><button>Delete all blogs</button></a>
            <br>

        </div>
    </div>
</div>

{% endblock %}

src/templates/blogs/front_page.html
{% extends "front_page_index.html" %}

{% block title %}BlogHome {% endblock %}

{% block body %}
 <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Blog Entries Column -->
        <div class="col-md-8">

          <h1 class="my-4">Fake Blog 1</h1>

          <!-- Blog Post -->
          <div class="card mb-4">
            <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
            <div class="card-body">
              <h2 class="card-title">Post Title</h2>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
              <a href="#" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              Posted on January 1, 2017 by
              <a href="#">Egbie Uku</a>
            </div>
          </div>

          <!-- Blog Post -->
          <div class="card mb-4">
            <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
            <div class="card-body">
              <h2 class="card-title">Post Title</h2>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
              <a href="#" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              Posted on January 1, 2017 by
              <a href="#">Egbie Uku</a>
            </div>
          </div>

          <!-- Blog Post -->
          <div class="card mb-4">
            <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
            <div class="card-body">
              <h2 class="card-title">Post Title</h2>
              <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>
              <a href="#" class="btn btn-primary">Read More &rarr;</a>
            </div>
            <div class="card-footer text-muted">
              Posted on January 1, 2017 by
              <a href="#">by Egbie</a>
            </div>
          </div>

          <!-- Pagination -->
          <ul class="pagination justify-content-center mb-4">
            <li class="page-item">
              <a class="page-link" href="#">&larr; Older</a>
            </li>
            <li class="page-item disabled">
              <a class="page-link" href="#">Newer &rarr;</a>
            </li>
          </ul>

        </div>

        <!-- Sidebar Widgets Column -->
        <div class="col-md-4">

          <!-- Search Widget -->
          <div class="card my-4">
            <h5 class="card-header">Search</h5>
            <div class="card-body">
              <div class="input-group">
                <input type="text" class="form-control" placeholder="Search for...">
                <span class="input-group-btn">
                  <button class="btn btn-secondary" type="button">Go!</button>
                </span>
              </div>
            </div>
          </div>

          <!-- Categories Widget -->
          <div class="card my-4">
            <h5 class="card-header">Categories</h5>
            <div class="card-body">
              <div class="row">
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Fake Category 1</a>
                    </li>
                    <li>
                      <a href="#">Fake Category 2</a>
                    </li>
                    <li>
                      <a href="#">Fake Category 3</a>
                    </li>
                  </ul>
                </div>
                <div class="col-lg-6">
                  <ul class="list-unstyled mb-0">
                    <li>
                      <a href="#">Fake Category 4</a>
                    </li>
                    <li>
                      <a href="#">Fake Category 5</a>
                    </li>
                    <li>
                      <a href="#">Fake Category 6</a>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <!-- Side Widget -->
          <div class="card my-4">
            <h5 class="card-header">Popular Posts</h5>
            <div class="card-body">
              This will feature the most popular posts
            </div>
          </div>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->


{% endblock %}