src/users/posts/models.py
from settings import STATIC_IMAGE_URL
from users.utils.generator.id_generator import gen_id
from users.utils.generator.date_generator import time_now as date_created
from users.records.record import Record
from users.utils.security.user_session import UserSession
from users.drafts.model import Draft
from users.comments.models import Comment
from users.utils.html_stripper import strip_html_tags


class Post(object):
    """The post allows the blog to create, _save and delete a post. The
        class should not be accessed directly and should only be accessed
        from the User blog class.
     """

    def __init__(self, user_id, child_blog_id, post_img=None):
        self._user_id = user_id
        self._child_blog_id = child_blog_id
        self._post_img = post_img
        self.Draft = Draft(self._child_blog_id, self._user_id)

    @staticmethod
    def get_post_by_id(post_id):
        """Test a post ID and returns that particular post."""

        post_data = Record.Query.Filter.filter_by_key_and_value({"child_post_id": post_id})
        return _ChildPost(**post_data) if post_data else None

    def get_all_posts(self):
        """Returns all posts belonging to a particular blog"""

        query = {"child_blog_id": self._child_blog_id,
                 "user_id": self._user_id, "post_live": True
                 }

        posts = Record.Query.find_all(query)
        return [_ChildPost(**post) for post in posts] if posts else None

    def create_new_post(self, title, post):
        """create_new_post(str, str) -> returns Post Object

        Takes a post form object containing the user post details
        and then creates a new post. Returns a post objects.
        """

        child_post_id = gen_id()
        publish_date = date_created()
        child_post = self._to_json(title, post, child_post_id, publish_date)

        Record.save(child_post)

        return _ChildPost(self._child_blog_id, self._user_id,
                          child_post_id, title, post, publish_date,
                          self._post_img
                          )

    @classmethod
    def delete_post(cls, post_id):
        """"""
        child_post = cls.get_post_by_id(post_id)
        Record.Delete.delete_post(child_post.child_blog_id, child_post.child_post_id)

    def _to_json(self, title, post, child_post_id, publish_date):
        """_to_json(post_obj, str) -> return a dictionary object

        Returns the data for post model object as json object

        :param
            `title`: Post title
            `description`: The post description.
            `child_post_id`: The post id for the post.
            `publish_date`: The date the post was created

        :returns
                Returns a json object
        """
        return {
            "user_id": self._user_id,
            "child_blog_id": self._child_blog_id,
            "child_post_id": child_post_id,
            "title": title,
            "post": post,
            "post_live": True,
            "publish_date": publish_date,
            "post_img": self._post_img,
        }


class _ChildPost(object):
    """This _ChildPost is a container and should not be accessed directly"""

    def __init__(self, child_blog_id, child_post_id, user_id, title,
                 post, publish_date, post_live, _id=None, post_img=None):
        self.child_post_id = child_post_id
        self.child_blog_id = child_blog_id
        self.user_id = user_id
        self.title = title
        self.post = post
        self.post_img = post_img
        self.post_live = post_live
        self.publish_date = publish_date
        self.author = UserSession.get_username()
        self._id = _id if _id else gen_id()
        self.Comment = Comment(self.child_blog_id, self.user_id, child_post_id)

    @staticmethod
    def html_strip(text):
        return strip_html_tags(text)

    def update_post(self, data):
        """"""
        Record.Update.update(field_name='child_post_id', field_id=self.child_post_id, data=data)

    def get_post_img(self, size):
        pass

src/users/comments/views.py
from flask import Blueprint, render_template, redirect, url_for

from users.comments.form import CommentForm
from users.users.users import UserBlog
from users.users.users import User
from users.utils.security.user_session import UserSession

comment_app = Blueprint("comment_app", __name__, url_prefix="/comments")


@comment_app.route("/delete/<blog_id>/<post_id>/<comment_id>")
def delete_comment(blog_id, post_id, comment_id):
    """"""
    post, blog = None, UserBlog()
    child_blog = blog.get_blog(blog_id)

    if child_blog:
        post = child_blog.Post.get_post_by_id(post_id)
    if post:
        post.Comment.delete_comment(comment_id)

    return redirect(url_for("posts_app.post_permalink", blog_id=blog_id, post_id=post_id, comment_id=comment_id))


@comment_app.route("/edit/<user_id>/<blog_id>/<post_id>/<comment_id>")
def edit_comment(user_id, blog_id, post_id, comment_id):
    # ToDo
    # Write the function needed to edit comments.
    pass

src/users/drafts/views.py
from flask import Blueprint, render_template, url_for, redirect, abort

from users.utils.generator.msg import Message
from users.users.users import UserBlog
from users.posts.form import PostForm
from users.posts.views import get_updated_data

drafts_app = Blueprint("drafts_app", __name__, url_prefix="/drafts")


@drafts_app.route("/drafts/<blog_id>", methods=['GET', 'POST'])
def save_to_drafts(blog_id):
    """"""

    form = PostForm()

    if form.validate_on_submit():
        child_blog = _get_blog(blog_id)
        child_blog.Post.Draft.save(form)

        Message.display_to_gui_screen("The newly created post has been saved to draft section")
        return redirect(url_for('drafts_app.get_drafts', blog_id=blog_id))

    return render_template('posts/new_post.html', form=form, blog_id=blog_id)


@drafts_app.route("/<blog_id>/drafts/all", methods=['GET', 'POST'])
def get_drafts(blog_id):
    """"""

    child_blog = _get_blog(blog_id)
    drafts = child_blog.Post.Draft.get_all_draft_posts()
    return render_template("drafts/drafts.html", blog_id=blog_id, drafts=drafts, num_of_drafts=len(drafts))


@drafts_app.route('/view/<blog_id>/<draft_id>', methods=['GET', 'POST'])
def view_draft(blog_id, draft_id):
    """"""
    child_blog = _get_blog(blog_id)
    edit_draft = True

    assert child_blog or abort(404)

    draft = child_blog.Post.Draft.get_draft_post(draft_id, to_class=True)

    form = PostForm(obj=draft)

    if form.validate_on_submit():

        draft_data = get_updated_data(form, draft)
        if draft_data:
            draft.update_draft(draft_data)
            Message.display_to_gui_screen("You post has successfully been updated.")
            return redirect(url_for("drafts_app.get_drafts", blog_id=blog_id))
    return render_template('posts/new_post.html', form=form, blog_id=blog_id, draft_id=draft_id,
                           edit_post=False, edit_draft=edit_draft)


@drafts_app.route("/<blog_id>/<draft_id>/publish", methods=['GET', 'POST'])
def publish(blog_id, draft_id):
    """"""

    child_blog = _get_blog(blog_id)
    draft_form = child_blog.Post.Draft.get_draft_post(draft_id)
    child_blog.Post.create_new_post(draft_form.get('title'), draft_form.get('post'))
    child_blog.Post.Draft.delete_draft(draft_id)

    Message.display_to_gui_screen("The draft with the title '{}' has been published.".format(draft_form.get('title')))
    return redirect(url_for('drafts_app.get_drafts', blog_id=blog_id))


@drafts_app.route("/delete/<blog_id>/<draft_id>")
def delete_draft(blog_id, draft_id):
    """"""

    child_blog = _get_blog(blog_id)
    child_blog.Post.Draft.delete_draft(draft_id)

    Message.display_to_gui_screen("The draft post has been deleted.")
    return redirect(url_for('drafts_app.get_drafts', blog_id=blog_id))


def _get_blog(blog_id):
    """"""
    blog = UserBlog()
    return blog.get_blog(blog_id)

src/users/login/views.py
from flask import Blueprint, render_template, request, redirect, url_for

from users.login.form import LoginForm
from users.users.users import User
from users.utils.security.user_session import UserSession
from users.utils.generator.msg import Message

login_app = Blueprint('login_app', __name__)


@login_app.route('/login', methods=['GET', 'POST'])
def login():
    """Allows the user to login to the application using the GUI"""

    form, error = LoginForm(), False

    _is_next_in_url()

    if UserSession.get_login_token():
        return _redirect_user_to_blog_creation_page()

    elif form.validate_on_submit():

        user = User.get_account_by_username(username=form.username.data)

        if user:
            email_status = user.get_email_confirmed_status()

            if email_status == 'EMAIL_CONFIRMED':

                if user.is_login_valid(password=form.password.data):
                    user.login()
                    return _redirect_user_to_url_in_next_if_found_or_to_blog_creation_page()

                error = _display_error_msg()

            else:
                error = _display_error_msg(email_status)
        else:
            error = _display_error_msg()

    return render_template("login/login.html", form=form, error=error)


def _display_error_msg(error="Incorrect username and password"):
    """"""
    Message.display_to_gui_screen(error)
    return True


def _is_next_in_url():
    """"""
    if request.method == 'GET' and request.args.get('next'):
        UserSession.add_next_url(request.args.get('next'))


def _redirect_user_to_url_in_next_if_found_or_to_blog_creation_page():
    """"""

    if UserSession.get_value_by_key('next'):
        next = UserSession.get_value_by_key('next')
        UserSession.remove_next_url()
        return redirect(next)
    return _redirect_user_to_blog_creation_page()


def _redirect_user_to_blog_creation_page():
    """Redirects the user to the blog creation page"""
    return redirect(url_for('blogs_app.blog'))

src/users/posts/views.py
from flask import Blueprint, render_template, url_for, redirect, abort

from users.posts.form import PostForm
from users.decorators import login_required
from users.users.users import UserBlog
from users.utils.generator.msg import Message
from users.utils.generator.date_generator import time_now
from users.comments.form import CommentForm

posts_app = Blueprint('posts_app', __name__, url_prefix="/posts")


@posts_app.route('/new/<blog_id>', methods=['GET', 'POST'])
@login_required
def new_post(blog_id):
    """Takes a blog id and creates a new post within that blog"""

    form = PostForm()
    edit_draft = False

    if form.validate_on_submit():

        child_blog = _get_blog(blog_id)
        child_blog.Post.create_new_post(form.title.data, form.post.data)

        Message.display_to_gui_screen("The post was created successfully")
        return redirect(url_for('posts_app.posts', blog_id=blog_id))

    return render_template('posts/new_post.html', form=form, blog_id=blog_id, edit_post=False, edit_draft=edit_draft)


@posts_app.route('/<blog_id>')
@login_required
def posts(blog_id):
    """Takes a blog id and returns all posts associated with that blog"""

    child_blog = _get_blog(blog_id)

    assert child_blog or abort(404)
    return render_template("posts/posts.html", posts=child_blog.Post.get_all_posts(),
                           blog_id=blog_id, blog_name=child_blog.blog_name)


@posts_app.route('/edit/<blog_id>/<post_id>', methods=['GET', 'POST'])
@login_required
def edit_post(blog_id, post_id):
    """"""

    child_blog = _get_blog(blog_id)
    edit_draft = False

    assert child_blog or abort(404)

    post = child_blog.Post.get_post_by_id(post_id)
    form = PostForm(obj=post)

    if form.validate_on_submit():

        post_data = get_updated_data(form, post)

        if post_data:
            post.update_post(post_data)
            Message.display_to_gui_screen("You post has successfully been updated.")
            return redirect(url_for("posts_app.posts", blog_id=blog_id))

    return render_template('posts/new_post.html', form=form, blog_id=blog_id, post_id=post_id,
                           edit_post=True, edit_draft=edit_draft)


@posts_app.route('/<blog_id>/<post_id>')
@login_required
def delete_post(blog_id, post_id):
    """"""

    child_blog = _get_blog(blog_id)
    child_blog.Post.delete_post(post_id)

    Message.display_to_gui_screen("The post has successfully been deleted")
    return redirect(url_for("posts_app.posts", blog_id=blog_id))


@posts_app.route("/mode/preview/<blog_id>", methods=['GET', 'POST'])
@login_required
def post_preview(blog_id):
    """Allows the user to preview a post before it is published"""

    form = PostForm()

    if form.validate_on_submit():
        return render_template("posts/post_preview.html", form=form, date=time_now())
    return redirect(url_for("posts_app.new_post", blog_id=blog_id))


@posts_app.route("/permalink/<blog_id>/<post_id>", methods=['GET', 'POST'])
def post_permalink(blog_id, post_id):
    """"""
    form = CommentForm()

    child_blog = _get_blog(blog_id)

    post = child_blog.Post.get_post_by_id(post_id)

    if form.validate_on_submit():
        post.Comment.save_comment(comment=form.comment.data)
        return redirect(url_for("posts_app.post_permalink", blog_id=blog_id, post_id=post_id))

    return render_template("posts/post_permalink.html", form=form, post=post)


def _get_blog(blog_id):
    """"""
    blog = UserBlog()
    return blog.get_blog(blog_id)


def get_updated_data(form, post_obj):
    """get_updated_data(form_obj, post_obj) -> return dict

    Checks if the user has updated their data. If the data has
    been updated returns only the updated data otherwise returns
    an empty dictionary.
    """

    data = {}

    if form.title.data != post_obj.title:
        data.update({"title": form.title.data})
    if form.post.data != post_obj.post:
        data.update({"post": form.post.data})
    return data

src/templates/posts/new_post.html
{% extends "index.html" %}
{% block title %} New post {% endblock %}

{% block body %}

<div class="container">
    <div id='creation' class="row">

        {% include "dashboard/dashboard.html" %}

        <div class="col-md-offset-1 col-lg-9">

            {% from "__formhelpers.html" import render_field %}

            {% if edit_post %}
                <h2> Edit Post </h2>
            {% elif edit_draft %}
                <h2> Edit draft </h2>
            {% else %}
                <h2> Create New Post</h2>
            {% endif %}

            <form method="POST" action="{{ url_for('posts_app.new_post', blog_id=blog_id) }}" role="form" enctype="multipart/form-data">

                <div class="panel-body">

                    {{ form.hidden_tag() }}
                    {{ render_field(form.title, class='form-control') }}
                    {{ render_field(form.post, rows="10", class='form-control') }}
                    {{ render_field(form.image, class='form-control') }}

                    <br>

                    {% if edit_post %}
                    <button type="submit" name="update post" formaction="{{ url_for('posts_app.edit_post', blog_id=blog_id, post_id=post_id) }}">Update post</button>

                    {% elif edit_draft %}
                        <button type="submit" name="update post" formaction="{{ url_for('drafts_app.view_draft', blog_id=blog_id, draft_id=draft_id) }}">Update draft</button>
                    {% else %}
                    <button type="submit">Save and post</button>
                    {% endif %}

                    {% if edit_draft %}
                        <button type="submit" name="save draft" formaction="{{ url_for('drafts_app.save_to_drafts', blog_id=blog_id) }}">Save as new draft</button>
                    {% else %}
                        <button type="submit" name="save draft" formaction="{{ url_for('drafts_app.save_to_drafts', blog_id=blog_id) }}">Save as draft</button>
                    {% endif %}
                    <button type="submit" name="preview" formaction="{{ url_for('posts_app.post_preview', blog_id=blog_id) }}">Preview</button>

                </div>

            <br>


            </form>
        </div>

    </div>

    </div>

{% endblock %}

src/templates/posts/post_permalink.html
{% extends "index.html" %}
{% block title %}{{ post.title.title() }}{% endblock %}

{% block body %}

<!-- Page Content -->
<div class="container">
    <div class="row">
        <div class="col-md-offset-4 col-md-7">

            <!-- Title -->
            <h1 class="mt-4">{{ post.title.title() }}</h1>

            <!-- Author -->
            <p class="lead">
                by
                {% if session.username %}
                    <a href="#">{{ session.username.title() }}</a>
                {% endif %}
            </p>

            <hr>

            <!-- Date/Time -->
            <p> Created on <strong>{{ post.publish_date.strftime('%c') }}</strong></p>

            <hr>

            <!-- Image -->
            {% if post.post_img %}
                <img class="img-fluid rounded" src="{{ url_for('static', filename=post.get_post_img('xlarge')) }}">
            {% else %}
                <img class="img-fluid rounded" src="http://placehold.it/400x400" alt="">
            {% endif %}

            <hr>

            <!-- Post Content -->
            {{ post.post | safe }}

            <hr>
            <input type="button" value="Back to posts" onclick="window.history.back()" />
            <br><br>

            {% from "__formhelpers.html" import render_field %}


            <form method="POST"
                  action="{{ url_for('posts_app.post_permalink', blog_id=post.child_blog_id, post_id=post.child_post_id) }}"
                  role="form">

                {{ form.hidden_tag() }}
                {{ render_field(form.comment, rows="5", class="form-control") }}

                {% if session.username %}
                    Post your comments

                    <br><br>
                    <button type="submit">Post comment</button>

                {% else %}

                    You must be logged into to make a comment.
                    <a href="{{ url_for('login_app.login') }}">login</a> |
                    <a href="{{ url_for('registration_app.register_user') }}">register</a>
                {% endif %}

            </form>


            <br><br>
            <h2>Comments</h2>
            <hr>
            <br>

            {% for comment in post.Comment.get_all_comments() %}
            <div class="card">
                <div class="card-header">
                    Username: <b>{{ session.username }} </b>
                    <br>
                    Commented on the post titled <strong>{{ post.title.title()}}</strong> on the <b>{{ comment.commented_on.strftime('%c') }}</b>

                </div>

                <div class="card-block">
                    <br>
                        {{ comment.comment }}

                    {% if session.username %}
                        <p class="float-sm-right">

                            <br>
                        <a href="#">Edit</a> |
                        <a href="{{ url_for('comment_app.delete_comment',blog_id=comment.child_blog_id,
                                             post_id=comment.post_id,comment_id=comment.comment_id)
                                  }}">Delete</a>
                        </p>
                        <br>
                        <br>
                    {% endif %}
                </div>
            </div>
            <br><br>

            {% endfor %}


        </div>
    </div>

</div>
<!-- /.row -->

</div>
<!-- /.container -->


{% endblock %}

src/templates/posts/post_preview.html
{% extends "index.html" %}
{% block title %}{{ form.title.data.title() }}-Preview{% endblock %}
{% block body %}

    <!-- Page Content -->
    <div class="container">

      <div class="row">

        <!-- Post Content Column -->
        <div class="col-md-offset-3 col-md-8">

          <!-- Title -->
          <h1 class="mt-4">This is a preview post page</h1>

          <h3 class="mt-4">{{ form.title.data.title() }}</h3>

          <!-- Author -->
          <p class="lead">
            by
            <a href="#">{{ session.username.title() }}</a>
          </p>

          <hr>

          <!-- Date/Time -->
          <p> Created on <strong>{{ date.strftime('%c') }}</strong></p>

          <hr>

          <!-- Preview Image -->
          <img class="img-fluid rounded" src="//placehold.it/400x400" alt="">
          <p> <b>Sorry, you cannot view your picture in preview mode</b></p>


          <hr>

          <!-- Post Content -->
          {{ form.post.data  | safe }}

          <hr>
          <input type="button" value="Go back to where I was" onclick="window.history.back()" />

          <hr>
          <h1><center>THIS IS A PREVIEW</center></h1>
          <hr>

        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->


{% endblock %}

src/templates/posts/posts.html
{% extends "index.html" %}

<!-- ToDo
    Add Bootsrap styling to the page to make it more pleasing to the eye.
-->
{% block title %}All posts{% endblock %}
{% block body %}

<br>
<div class="container">
    <div class="row">

        <div class="col-md-12">

            {% include "__flash_messages.html" %}
            {% if posts %}

            <div class="jumbotron">
                 <h1>Blog name: {{ blog_name.title() }}</h1>
            </div>

             <h3><u>List of posts</u></h3>

            <table class="table table-striped">

                <thead>
                <tr>
                    <th>#</th>
                    <th>Post Name</th>
                    <th>Description</th>
                    <th>Author</th>
                    <th>Published date</th>
                    <th>Edit/Delete</th>
                </tr>
                </thead>

                <tbody>

                {% for post in posts %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <td><a href="{{ url_for('posts_app.post_permalink', blog_id=post.child_blog_id, post_id=post.child_post_id) }}">{{ post.html_strip(post.title)| truncate(20) }}</a></td>
                    <td>{{ post.html_strip(post.post) | truncate(30) }}</td>
                    <td>{{ post.author.title() | truncate(10) }}</td>
                    <td>{{ post.publish_date.strftime('%c') }}</td>
                    <td>

                        <a href="{{ url_for('posts_app.edit_post', blog_id=post.child_blog_id, post_id=post.child_post_id) }}">
                            <button>Edit</button>
                            <a/>
                            |
                            <a href="{{ url_for('posts_app.delete_post', blog_id=post.child_blog_id, post_id=post.child_post_id) }}">
                                <button>Delete</button>
                                <a/>


                </tr>
                {% endfor %}
                </tbody>
            </table>

            {% else %}
            <div class="jumbotron">
                You currently have no posts
            </div>
            {% endif %}


            <a href="{{ url_for('blogs_app.blog', blog_id=blog_id) }}"><button type="button"><< Back to my blogs</button></a>
            <a href="{{ url_for('posts_app.new_post', blog_id=blog_id) }}"><button type="button">Create New post</button></a>
            <a href="{{ url_for('drafts_app.get_drafts', blog_id=blog_id) }}"><button type="button">View drafts</button></a>
            <br>
            <br>

        </div>
    </div>
</div>

{% endblock %}