src/users/drafts/views.py
from flask import Blueprint, render_template, url_for, redirect, abort

from users.utils.generator.msg import Message
from users.users.users import UserBlog
from users.posts.form import PostForm
from users.posts.views import get_updated_data

drafts_app = Blueprint("drafts_app", __name__, url_prefix="/drafts")


@drafts_app.route("/drafts/<blog_id>", methods=['GET', 'POST'])
def save_to_drafts(blog_id):
    """"""

    form = PostForm()

    if form.validate_on_submit():
        child_blog = _get_blog(blog_id)
        child_blog.Post.Draft.save(form)

        Message.display_to_gui_screen("The newly created post has been saved to draft section")
        return redirect(url_for('drafts_app.get_drafts', blog_id=blog_id))

    return render_template('posts/new_post.html', form=form, blog_id=blog_id)


@drafts_app.route("/<blog_id>/drafts/all", methods=['GET', 'POST'])
def get_drafts(blog_id):
    """"""

    child_blog = _get_blog(blog_id)
    drafts = child_blog.Post.Draft.get_all_draft_posts()
    return render_template("drafts/drafts.html", blog_id=blog_id, drafts=drafts, num_of_drafts=len(drafts))


@drafts_app.route('/view/<blog_id>/<draft_id>', methods=['GET', 'POST'])
def view_draft(blog_id, draft_id):
    """"""
    child_blog = _get_blog(blog_id)
    edit_draft = True

    assert child_blog or abort(404)

    draft = child_blog.Post.Draft.get_draft_post(draft_id, to_class=True)

    form = PostForm(obj=draft)

    if form.validate_on_submit():

        draft_data = get_updated_data(form, draft)
        if draft_data:
            draft.update_draft(draft_data)
            Message.display_to_gui_screen("You post has successfully been updated.")
            return redirect(url_for("drafts_app.get_drafts", blog_id=blog_id))
    return render_template('posts/new_post.html', form=form, blog_id=blog_id, draft_id=draft_id,
                           edit_post=False, edit_draft=edit_draft)


@drafts_app.route("/<blog_id>/<draft_id>/publish", methods=['GET', 'POST'])
def publish(blog_id, draft_id):
    """"""

    child_blog = _get_blog(blog_id)
    draft_form = child_blog.Post.Draft.get_draft_post(draft_id)
    child_blog.Post.create_new_post(draft_form.get('title'), draft_form.get('post'))
    child_blog.Post.Draft.delete_draft(draft_id)

    Message.display_to_gui_screen("The draft with the title '{}' has been published.".format(draft_form.get('title')))
    return redirect(url_for('drafts_app.get_drafts', blog_id=blog_id))


@drafts_app.route("/delete/<blog_id>/<draft_id>")
def delete_draft(blog_id, draft_id):
    """"""

    child_blog = _get_blog(blog_id)
    child_blog.Post.Draft.delete_draft(draft_id)

    Message.display_to_gui_screen("The draft post has been deleted.")
    return redirect(url_for('drafts_app.get_drafts', blog_id=blog_id))


def _get_blog(blog_id):
    """"""
    blog = UserBlog()
    return blog.get_blog(blog_id)

src/templates/drafts/drafts.html
{% extends "index.html" %}

{% block title %}Drafts {% endblock %}
{% block body %}

<!-- ToDo
    Add Bootstrap styling to the page to make it more pleasing to the eye.
-->

<div class="container">
    <div class="row">

        <div class="col-md-12">

            {% if drafts %}

            {% include "__flash_messages.html" %}

            <br><br>
            <div class="jumbotron">
                You have a total of <strong>{{ num_of_drafts }}</strong> posts not yet published
                <br>
            </div>

            <h3><u>List of drafts</u></h3>

            <table class="table table-striped">

                <thead>
                <tr>
                    <th>#</th>
                    <th>Draft</th>
                    <th>Description</th>
                    <th>Creation date</th>
                    <th>View/Publish/Delete</th>
                </tr>
                </thead>

                <tbody>

                {% for draft in drafts %}
                <tr>
                    <th scope="row">{{ loop.index }}</th>
                    <td><a href="{{ url_for('drafts_app.view_draft', blog_id=blog_id, draft_id=draft.draft_id) }}">{{ draft.html_strip(draft.title) | truncate(20) }}</a></td>
                    <td>{{ draft.html_strip(draft.post) | truncate(40) | safe }} </td>
                    <td>{{ draft.date_created.strftime('%c') }}</td>

                    <td>

                        <a href="{{ url_for('drafts_app.view_draft', blog_id=blog_id, draft_id=draft.draft_id) }}"><button>View</button></a>
                        |
                        <a href="{{ url_for('drafts_app.publish', blog_id=blog_id, draft_id=draft.draft_id) }}"><button>Publish</button></a>
                        |
                        <a href="{{ url_for('drafts_app.delete_draft', blog_id=blog_id, draft_id=draft.draft_id) }}"><button>Delete</button></a>

                    </td>
                </tr>
                {% endfor %}

                </tbody>

            </table>

            {% else %}
            <div class="jumbotron">
                You currently have no saved drafts.
                <br>
                Saving a draft allows you to keep a post you aren't ready to publish yet.
            </div>
            {% endif %}
            <a href="{{ url_for('posts_app.posts', blog_id=blog_id) }}">
                <button type="button"><< Back to my posts</button>
            </a>
        </div>
    </div>
</div>

{% endblock %}